version: '3'

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

services:

  app:
    image: ambientum/php:7.2-nginx
    container_name: laravel-docker-php
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  mysql:
    image: ambientum/mysql:5.7
    container_name: laravel-docker-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbpassword
      - MYSQL_DATABASE=dbdatabase
      - MYSQL_USER=dbusername
      - MYSQL_PASSWORD=dbpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-docker-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: dbusername
      PMA_PASSWORD: dbpassword
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    restart: always
    ports:
     - 8001:80
    volumes:
     - /sessions

  cache:
    image: ambientum/redis:3.2
    container_name: laravel-docker-redis
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  queue:
    image: ambientum/php:7.0
    container_name: laravel-docker-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-docker-mailhog
    ports:
      # 1025: this port is used for SMTP, You will not need to uncommed this here, unless you have a very
      #       specific use case.
      # - 1025:1025
      # 8025: this port is used for the web interface on mailhog.
      #       It's just like a email customers. that will list all emails you've sent.
      - 1025:1025
      - 8025:8025
